# Generated by Django 5.0.3 on 2024-04-08 02:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="detalle",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reserva",
            name="duracion",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="reserva",
            name="fecha",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="reserva",
            name="hora",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
