# Generated by Django 5.0.3 on 2024-04-08 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_reserva_detalle_reserva_duracion_reserva_fecha_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("disponible", models.BooleanField(default=True)),
                ("capacidad", models.IntegerField()),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name="reserva",
            old_name="detalle",
            new_name="descripcion",
        ),
        migrations.AlterField(
            model_name="reserva",
            name="duracion",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="consultorio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservas",
                to="bookings.consultorio",
            ),
        ),
    ]
