# Generated by Django 5.0.3 on 2024-04-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_masajista_alter_consultorio_descripcion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="masajista",
            name="documento",
            field=models.IntegerField(default=None),
        ),
    ]
